serial:
  baudrate: 115200
  ports_prefix: /dev/ttyACM

systems:
  - profile: master
    ip: 10.53.18.1 # 169.254.1.51
    port: 5050
    system_codes:
      R-17: C1062208
    start: true

  - profile: slave
    ip: 10.53.18.54 # 169.254.1.11
    port: 5050
    system_codes:
      T-07: C1062201
      R-07: C2062201
    start: false

socket_server:
  protocol: https
  host: beta.handddle.com
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsaW5lIiwibmFtZSI6IkhhbmRkZGxlIiwiaWF0IjoxNTE2MjM5MDIyfQ.pP40SSJan5Zpw946k3DzukSnkmrcJOT3pO0VVUY0aew
  path: /socket
  event: farm command

gui:
  host: 127.0.0.1
  port: 8080

broadcast:
  uid: CFFFFFFF

watchdog_interval: 4 # Seconds

api_server:
  protocol: https
  host: beta.handddle.com
  licence_key: HANDDDLE

influxdb:
  protocol: https
  host: data.beta.handddle.com
  org: handddle
  token: 5GEStuLlJu6-GqL3nDDxknaVTHOiB24xa2GlS5-7yswL2EtPOmhlBmldLLRohNBIoeM9FQ8-rHCKrxj3iZONgQ==
  bucket: farm_data

scanner:
  serial_base: 0x18502
  baudrate: 9600

logging:
  directory: logs
  level: DEBUG
  console: true

debug: false

demo: false

display_data: true
